aws_ami="ami-xxxx"
subnet_id="subnet-xxxxx"
security_group = "default"
master_instance_type = "t2.medium"
node_instance_type = "t2.medium"
num_glusterfs = "3"
num_glusterfs_registry = "3"
num_nodes = "3"
num_infra = "1"
num_masters = "1"
prefix= "mjudeiki-"
postfix="-preserve"

